
alias ls="ls -hF"
alias ll="ls -lahF"
alias "cd.."="cd ../"
alias mkdir="mkdir -p"
alias cp="cp -r"
alias scp="scp -r"
alias ga="git add"
alias gc="git commit -m"
alias gs="git status"
alias gd="git diff"
alias gf="git fetch"
alias gm="git merge"
alias gr="git rebase"
alias gp="git push"
alias gu="git unstage"
alias gg="git graph"
alias gco="git checkout"
alias gcs="git commit -S -m"
alias gpr="hub pull-request"
alias ag="ag --color --color-line-number '0;35' --color-match '46;30' --color-path '4;36'"
alias tree='tree -CAFa -I "CVS|*.*.package|.svn|.git|.hg|node_modules|bower_components" --dirsfirst'

alias k="kak"
alias v="nvim"
alias e="emacsclient -c"
alias rm="rm -r"
alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"
alias ctags="$(brew --prefix)/bin/ctags"
alias gss="git-fshow"
alias be="bundle exec"
alias rs="be rails server"
alias rc="be rails console"
alias mg="be rake db:migrate"
alias mt="RAILS_ENV=test be rake db:drop; RAILS_ENV=test be rake db:create; RAILS_ENV=test be rake db:migrate"
alias rb="be rake db:rollback"

alias c="bundle exec cucumber -p circle"
alias cs="SKIP_WEBPACK_IN_TESTS=true bundle exec cucumber -p circle"

alias did="vim +'normal Go' +'r!date' ~/did.txt"
